# Generated by Django 4.2 on 2023-04-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='profile_image',
            field=models.TextField(default=''),
        ),
    ]
