# Generated by Django 4.2 on 2023-04-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_anime_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime_list',
            name='data',
            field=models.JSONField(default=False),
        ),
    ]
